### PR TITLE
some bootstrap tweaks

### PR DESCRIPTION
**Pull request by madsi1m**
Make things a little nicer

### CODE REVIEW

**Comment by monkeyiq** [comment]
I might abstract out the custom-checkbox vs custom-switch to allow either one to be selected as a configuration option. I imagine that the particular choice would depend on what each site admin likes the most & what fits their overall site most.

Thanks for the PR! I will take a closer look shortly and likely do the update I mentioned above soon after merging.

**Comment by madsi1m** [comment]
Added more things to make your life a little harder...

**Comment by madsi1m** [comment]
Hi @monkeyiq I think I'm done with UI tweaks on the upload page. I wouldn't bother at this stage abstracting switches we have been using switches in production for a few years now.

**Comment by monkeyiq** [comment]
I should probably preface this in that it might go to a designer before being formally merged. That said, IMHO to me it seems a little clearer in stage 2 of the upload having the old 
```
"you are going to create a link" ... or button<click here to send email>
```
instead of as two buttons.

Thanks for the PR! Merging...

**Comment by madsi1m** [comment]
will this be pushed to filesender repo so others can poke (and find) it?

**Comment by monkeyiq** [comment]
I'm happy enough to push it over to the filesender repo now as a branch. I just did a really small update to my local copy and pushed to my repo. I think if I move it over to the main filesender repo then I will be more inclined to use my normal model of submitting my changes through PRs so other can see them too.

**Comment by monkeyiq** [comment]
one downside of the language selector being below the menu entries is that the tabs on for example the guests page are lower than the menu now.

**Comment by madsi1m** [comment]
yeh, i moved it down under the menu, to look better, otherwise too much white space up the top (or yellow in your case). I did consider having it in the footer but i think users will miss it. Other sites have a flag icon of current language and clicking it shows a down down. I might look into that if you like and then it can live top right.

**Comment by monkeyiq** [comment]
I guess one of the big questions would be if the board wants to merge this into a release before a designer has also given feedback.

**Comment by madsi1m** [comment]
I wouldn't yet, but a bootstrap or new ui branch might be interesting with constant pulls from dev branch

**Comment by monkeyiq** [comment]
I have created a branch on filesender/filesender with the bootstrap code in it https://github.com/filesender/filesender/tree/2021/bootstrap

The code in that branch is a patch applied to development in the main repo, so it should be release 2.22 plus bootstrap at the moment.

**Pull request merged**
